security:
  jwt:
    token:
      secret-key: S3cR37-k31
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financeiro?useTimezone=true&serverTimezone=UTC
    username: root
    password: 020269
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 
    show-sql: true
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true